from PyQt5.QtWidgets import (QCheckBox, QGroupBox, QComboBox, QLineEdit)
from PyQt5.QtWidgets import (QLabel, QPushButton, QVBoxLayout)


def Add(self):
    self.Acheck = QCheckBox('Add Keys', self)
    self.Acheck.stateChanged.connect(self.Atoggle)
    self.layout.addWidget(self.Acheck)
    self.AgroupBox = QGroupBox("")
    self.AcomboBox = QComboBox()
    self.AcomboBox.addItem('Select your drive')
    self.AcomboBox.setMinimumWidth(300)
    device_list = self.listEncryptedDevices()
    for ele in device_list:
        self.AcomboBox.addItem(ele['label'])

    label = QLabel()
    label.setText("Enter any existing password")
    self.Atextbox = QLineEdit()
    #self.Atextbox.setEnabled(False)
    self.Atextbox.setEchoMode(QLineEdit.Password)
    self.Atextbox.setMaxLength(10)
    #label_t = QLabel()
    #label_t.setText("Enter user password")
    #self.Atextbox_t = QLineEdit()
    #self.Atextbox_t.setEchoMode(QLineEdit.Password)
    label1 = QLabel()
    label1.setText("Enter your new password")
    self.Atextbox1 = QLineEdit()
    self.Atextbox1.setEchoMode(QLineEdit.Password)
    #self.Atextbox1.setEnabled(False)
    self.Atextbox1.setMaxLength(10)
    label2 = QLabel()
    label2.setText("Verify your password")
    self.Atextbox2 = QLineEdit()
    self.Atextbox2.setEchoMode(QLineEdit.Password)
    #self.Atextbox2.setEnabled(False)
    self.Atextbox2.setMaxLength(10)
    self.Abtn1 = QPushButton("Finish", self)
    self.Abtn1.clicked.connect(self.password_fun_add)
    vbox = QVBoxLayout()
    vbox.addWidget(self.AcomboBox)
    #vbox.addWidget(label_t)
    #vbox.addWidget(self.Atextbox_t)
    vbox.addWidget(label)
    vbox.addWidget(self.Atextbox)
    vbox.addWidget(label1)
    vbox.addWidget(self.Atextbox1)
    vbox.addWidget(label2)
    vbox.addWidget(self.Atextbox2)
    vbox.addWidget(self.Abtn1)
    vbox.addStretch(1)
    self.AgroupBox.setLayout(vbox)
    self.layout.addWidget(self.AgroupBox)
